### ISSUE TITLE
Board not detected

### ISSUE THREAD

**Issue by vincent0143** [raspberry-sharp/raspberry-sharp-io#103]
I'm trying to get my rpi zero working. I tested this on a rpi3b before and that worked after adding this:

> `Dictionary<string, string> boardSettings = (Dictionary<string, string>)Board.Current.GetType().
                GetField("settings", BindingFlags.Instance | BindingFlags.NonPublic).
                GetValue(Board.Current);
            boardSettings["Hardware"] = "<processor name>";`

but changing the processor name to the rpi zero processor (BCM2835) results in a null pointer exception. Does anyone have a suggestion to fix this?

**Comment by JTrotta** [comment]
I think we solved this issue. Lets try this
https://github.com/JTrotta/RaspberrySharp
