### ISSUE TITLE
nRF24L01 

### ISSUE THREAD

**Issue by genielabs** [raspberry-sharp/raspberry-sharp-io#11]
Hi,

would it possible to port the code from:

http://nrf24l01.codeplex.com/SourceControl/latest#Gralin.NETMF.Nordic.NRF24L01Plus/NRF24L01Plus.cs

to RaspberrySharp?

Thanks!

**Comment by HakanL** [comment]
I wonder if it may be better to create a separate project for the nRF24L01 implementation, using the Raspberry-sharp-io library as a dependency for the SPI interface.

**Comment by ebezine** [comment]
It would also be possible to include the implementation in the components assembly, but depending on the quantity of code involved in implementation, it may be considered as an independent project, yes.
