### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by gamondue** [raspberry-sharp/raspberry-sharp-io#22]
Is I2C working, in the lib? 
I am trying to connect an I2C Real Time Clock, but I don't understand how to read registrer # 2 on device of address 0x51. Tried by guessing, but no way. 
Can you access single registers inside the controlled device with your library?

**Comment by ebezine** [comment]
Hi @gamondue,

In order to get the RTC work, you'll have to implement the protocol (that is, the way data are exchanged over I2C between RTC and I2C host). Protocol is usually provided by spécifications.

**Comment by chkr1011** [comment]
@gamondue: You need to merge my pull request. The repeated start conditions are required to read data from registers.

**Comment by gamondue** [comment]
Thank you! As soon as I will have time, I will try.
