### ISSUE TITLE
Does not seem to support PI2

### ISSUE THREAD

**Issue by LocalJoost** [raspberry-sharp/raspberry-sharp-io#29]
Hi,

I have tried this with the Raspberry PI2 and it does not seem to support that. That is, even if I manually set the board revision to (default it seems to select 2) I cannot get a pin to work. Is that correct?

Also - maybe I am missing something - but where can I find sample usages?

**Comment by ebezine** [comment]
Hello,

Support for Raspberry Pi 2 has been added by @genielabs and included in the latest merge and Nuget publish.
This should help you to solve your issue.
