### ISSUE TITLE
Compiling with the latest build of mono on Raspberry Pi 2

### ISSUE THREAD

**Issue by gloveboxes** [raspberry-sharp/raspberry-sharp-io#33]
Hi, been successfully using the raspberry-sharp-io on Raspberry Pi 2.  I did an update-distribution today which took me to the latest build of Mono Develop and mono complete.  The Raspberry.IO.Interop project no longer compiles - get error message "The Dllimport attribute cannot be applied to a method that is a generic or constrained in a generic type". 

Is this an issue with the latest compiler or have I damaged my pi setup.  Cheers Dave

**Comment by ebezine** [comment]
This is the same issue as @Savij reported in #27
