### ISSUE TITLE
Don't found mscorlib.dll 2.0 version

### ISSUE THREAD

**Issue by abeiamob** [raspberry-sharp/raspberry-sharp-io#37]
Please,
I installed only mono-runtime and I found error using Raspberry-sharp:
"The assembly mscorlib.dll was not found or could not be loaded. It should have been installed in the `/usr/lib/mono/2.0/mscorlib.dll' directory."

Don't found nothing in the project using this version.

**Comment by ebezine** [comment]
Hello,

Did you try to install the full mono-complete module ?
