### ISSUE TITLE
I2C: Repeated start conditions are not supported

### ISSUE THREAD

**Issue by chkr1011** [raspberry-sharp/raspberry-sharp-io#38]
These conditions are used to read registers from port expanders like PCA9555. The library does not allow to write and read within the same transaction. This issue also prevents reading from EEPROMs etc.

**Comment by ebezine** [comment]
It seem you have solved this issue through Pull request #39.

**Comment by JTrotta** [comment]
It seems this enhancement not working with LTC2943, that needs reapeted Start conditions. Is this the right way to use it?

` I2cWriteAction writeAction = new I2cWriteAction(register);
            I2cReadAction readAction = new I2cReadAction(new byte[byteCount]);
            I2cTransaction transaction = new I2cTransaction(writeAction, readAction);
            Execute(transaction);
            return readAction.Buffer;
`

**Comment by chkr1011** [comment]
Hi,
yes this should work. I fixed acessing port expanders like PCA9555 or MAX7311 with this code. But I don't know what heppened in the meantime or of your device requires some other things.

I remember that there were some issues with the clock stretching feature which is not properly implemented in hardware. This results in several devices which are not working. But I don't remember if this was RaspberryPi 1 or RaspberryPi 2.

Best regards
Christian

**Comment by JTrotta** [comment]
@chkr1011 Thank you for reply. I'm testing library on RB3, and LTC2943 (fuel gauge sensor), but I can only read all register at time. So you suggest to check the clock?  The only way to do this is using an oscilloscope.
I'll let you know. Thank you very much

P.S. (you MQTT library is very cool!)

**Comment by chkr1011** [comment]
No there is nothing you can do and I assume this is fixed on Pi3 (it was a bug in hardware and not fixable in code). 

Thank you :-)

**Comment by JTrotta** [comment]
But I'm using Pi3/CM3 (industrial Compute Module 3), and cannot get it working. I suppose there must be something to let it work. This is the sequence:
![image](https://user-images.githubusercontent.com/2145654/30850532-11832348-a2a6-11e7-9ba1-2e3070bec036.png)

It's very similar to PCA9555:
![image](https://user-images.githubusercontent.com/2145654/30850738-c9059730-a2a6-11e7-8912-b609aab15bae.png)

**Comment by JTrotta** [comment]
I'm sorry, but this PR does not work at all. It does not sends a repeated started condition (oscilloscope checked).
I engineered a new working driver using c++ code from here : [https://github.com/NextThingCo/otto-runner/blob/master/lib/bcm2835.c](url)

Now it works. I'm publishing a PR,
Thank you.
