### ISSUE TITLE
Use Mono4 and .NET Core

### ISSUE THREAD

**Issue by JuergenGutsch** [raspberry-sharp/raspberry-sharp-io#40]
Since a week I worked with ASP.NET 5 (beta4) with Mono 4 on the Raspberry PI 2 and it works really graeat, but it seems that this project (also https://github.com/raspberry-sharp/raspberry-sharp-system) doesn't work with Mono4 or .NET Core. Would it be possible to make your projects compatible with the new Frameworks? I really would like to help to get this working.

**Comment by ebezine** [comment]
Hello,

More information is needed to understand the actual issue :
What kind of issues/errors did you notice while using Mono 4 and .NET Core ?

**Comment by neutmute** [comment]
fyi I am using i2c with this library on mono 4.0.2 and it is working fine on the pi2
