### ISSUE TITLE
Possible support for T6963C-driven displays

### ISSUE THREAD

**Issue by CommanderBjoern** [raspberry-sharp/raspberry-sharp-io#47]
Hello!
Firstly, thank you for this superb library! It already solves many of my problems I had to deal with like I/O expanders and I2C. 
One point I still can't handle with is my T6963C-Display...
So I would like to ask if it would be much of an effort for you to implement the support for T6963C-driven graphic displays?
For example writing text with a choosable font and size or displaying monochrome pictures.

Thanks and keep up the great work!
Greets, Bjoern

**Comment by ebezine** [comment]
Hello,

Thank you for your feedback and use of this library. Dealing with T6963C display may or  may not be a huge job, depending on protocol complexity. I would recommend downloading the Datasheet, and looking around for existing implementations in C or Python.

Unfortunately I cannot be of some help with this display :(
