### ISSUE TITLE
Fixed1L.cs contains extended characters in Latin encoding; needs to be saved as Unicode

### ISSUE THREAD

**Issue by reinux** [raspberry-sharp/raspberry-sharp-io#64]
Simple fix: File -> Save As -> Save with Encoding -> Unicode (65001).

**Comment by petergloor** [comment]
I can confirm this, I just run into this issue too.

**Comment by xlevel** [comment]
Submitted a pull request to fix this.

**Comment by xlevel** [comment]
I think this issue should now be closed after [this commit](https://github.com/raspberry-sharp/raspberry-sharp-io/commit/9165eac5f681e5b65bb88263274530fe7f6946e5) was merged in.
